@ReservationDeSalle__Back_HostAddress = http://localhost:5010


# Avec l'extention "REST Client"
# Tu peux tester les routes suivante juste en cliquant sur le texte "Send request"
# présente au dessus des GET/POST...

###


GET {{ReservationDeSalle__Back_HostAddress}}/room
Content-Type: application/json

###


GET {{ReservationDeSalle__Back_HostAddress}}/room/1
Content-Type: application/json

###

POST {{ReservationDeSalle__Back_HostAddress}}/room/
Content-Type: application/json

{
    "Name": "salle 1",
    "Picture": "room1_small",
    "Adress": "2 rue de la Paix",
    "AdressComplements": "",
    "Groupe": 2,
    "Capacity": 6,
    "Area": 20,
    "Surface": "interieur et exterieur",
    "IsAccessible": true
}


###

POST {{ReservationDeSalle__Back_HostAddress}}/room/
Content-Type: application/json

{
    "Name": "salle 2",
    "Picture": "room2_small",
    "Adress": "19 rue de Lacroix",
    "AdressComplements": "2ème porte à droite",
    "Groupe": 3,
    "Capacity": 10,
    "Area": 50,
    "IsAccessible": true,
    "Surface": "interieur et exterieur"
}

###

POST {{ReservationDeSalle__Back_HostAddress}}/room/
Content-Type: application/json

{
    "Name": "salle 3",
    "Picture": "room3_small",
    "Adress": "16 place des Grands Hommes",
    "AdressComplements": "2ème étage, 1ère porte à gauche",
    "Groupe": 1,
    "Capacity": 16,
    "Area": 150.25,
    "IsAccessible": true,
    "Surface": "interieur"
}

###

PUT {{ReservationDeSalle__Back_HostAddress}}/room/
Content-Type: application/json

{
    "Id": 1,
    "Name": "salle 1",
    "Picture": "room1_small",
    "Adress": "16 place des Grands Hommes",
    "AdressComplements": "2ème étage, 1ère porte à gauche",
    "Groupe": 1,
    "Capacity": 16,
    "Area": 150.25,
    "IsAccessible": true,
    "Surface": "interieur"
}

###


GET {{ReservationDeSalle__Back_HostAddress}}/user
Content-Type: application/json

###

POST {{ReservationDeSalle__Back_HostAddress}}/user/
Content-Type: application/json

{
    "Lastname": "Runser",
    "Firstname": "Aurelie",
    "Email": "aurelie.runser25@gmail.com",
    "Password": "vmk",
    "Company": "Ynov",
    "Job": "student",
    "Role": 0
}

###

POST {{ReservationDeSalle__Back_HostAddress}}/user/
Content-Type: application/json

{
    "Lastname": "Joestar",
    "Firstname": "Joseph",
    "Email": "joseph@joestar.com",
    "Password": "IamTheBest",
    "Company": "SpeedWagon Company",
    "Job": "Directeur",
    "Role": 1
}

###

PUT {{ReservationDeSalle__Back_HostAddress}}/user/
Content-Type: application/json

{
    "Id": 2,
    "Lastname": "Runser",
    "Firstname": "Aurelie",
    "Email": "la@la.com",
    "Password": "vmk",
    "Company": "Ynov",
    "Job": "student",
    "Role": 0
}

###

DELETE {{ReservationDeSalle__Back_HostAddress}}/user/4
Content-Type: application/json