@RoomBooking_Back__HostAddress = http://localhost:5010

###

GET {{RoomBooking_Back__HostAddress}}/room
Content-Type: application/json

###

GET {{RoomBooking_Back__HostAddress}}/room/1
Content-Type: application/json

###

POST {{RoomBooking_Back__HostAddress}}/room/
Content-Type: application/json

{
    "NewRoom":
    {
        "Name": "salle 1",
        "Picture": "room1_small",
        "Adress": "2 rue de la Paix",
        "AdressComplements": "",
        "Groupe": "Petite Réunion",
        "Capacity": 6,
        "Area": 20,
        "Surface": "interieur et exterieur",
        "IsAccessible": true
    },
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwiZW1haWwiOiJhdXJlbGllLnJ1bnNlcjI1QGdtYWlsLmNvbSIsIm5iZiI6MTczOTgxNTQ0MiwiZXhwIjoxNzM5OTAxODQyLCJpYXQiOjE3Mzk4MTU0NDJ9.jQB6phxyUZcQJvxTFbVVC0dkFt1XffeOw_y9jfJM_10"
}


###

POST {{RoomBooking_Back__HostAddress}}/room/
Content-Type: application/json

{
    "NewRoom":
    {
        "Name": "salle 2",
        "Picture": "room2_small",
        "Adress": "19 rue de Lacroix",
        "AdressComplements": "2ème porte à droite",
        "Groupe": "Grande Réunion",
        "Capacity": 10,
        "Area": 50,
        "IsAccessible": true,
        "Surface": "interieur et exterieur"
    },
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwiZW1haWwiOiJhdXJlbGllLnJ1bnNlcjI1QGdtYWlsLmNvbSIsIm5iZiI6MTczOTgxNTQ0MiwiZXhwIjoxNzM5OTAxODQyLCJpYXQiOjE3Mzk4MTU0NDJ9.jQB6phxyUZcQJvxTFbVVC0dkFt1XffeOw_y9jfJM_10"
}

###

POST {{RoomBooking_Back__HostAddress}}/room/
Content-Type: application/json

{
    "NewRoom":
    {
        "Name": "salle 3",
        "Picture": "room3_small",
        "Adress": "16 place des Grands Hommes",
        "AdressComplements": "2ème étage, 1ère porte à gauche",
        "Groupe": "Fête",
        "Capacity": 16,
        "Area": 150.25,
        "IsAccessible": true,
        "Surface": "interieur"
    },
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwiZW1haWwiOiJhdXJlbGllLnJ1bnNlcjI1QGdtYWlsLmNvbSIsIm5iZiI6MTczOTgxNTQ0MiwiZXhwIjoxNzM5OTAxODQyLCJpYXQiOjE3Mzk4MTU0NDJ9.jQB6phxyUZcQJvxTFbVVC0dkFt1XffeOw_y9jfJM_10"
}

###

PUT {{RoomBooking_Back__HostAddress}}/room/
Content-Type: application/json

{
    "Id": 1,
    "Name": "salle 1",
    "Picture": "room1_small",
    "Adress": "16 place des Grands Hommes",
    "AdressComplements": "2ème étage, 1ère porte à gauche",
    "Groupe": 1,
    "Capacity": 16,
    "Area": 150.25,
    "IsAccessible": true,
    "Surface": "interieur"
}

###


GET {{RoomBooking_Back__HostAddress}}/user
Content-Type: application/json

###

POST {{RoomBooking_Back__HostAddress}}/user/
Content-Type: application/json

{
    "Lastname": "Runser",
    "Firstname": "Aurelie",
    "Email": "aurelie.runser25@gmail.com",
    "Password": "vmk",
    "Company": "Ynov",
    "Job": "student",
    "Role": "admin"
}

###

POST {{RoomBooking_Back__HostAddress}}/user/
Content-Type: application/json

{
    "Lastname": "Joestar",
    "Firstname": "Joseph",
    "Email": "joseph@joestar.com",
    "Password": "IamTheBest",
    "Company": "SpeedWagon Company",
    "Job": "Directeur",
    "Role": "user"
}

###

PUT {{RoomBooking_Back__HostAddress}}/user/
Content-Type: application/json

{
    "Id": 2,
    "Lastname": "Runser",
    "Firstname": "Aurelie",
    "Email": "la@la.com",
    "Password": "vmk",
    "Company": "Ynov",
    "Job": "student",
    "Role": 0
}

###

DELETE {{RoomBooking_Back__HostAddress}}/user/2
Content-Type: application/json

###

GET {{RoomBooking_Back__HostAddress}}/booking
Content-Type: application/json

###

GET {{RoomBooking_Back__HostAddress}}/booking/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhdXJlbGllLnJ1bnNlcjI1QGdtYWlsLmNvbSIsIm5iZiI6MTczNzkxMTU5MiwiZXhwIjoxNzM3OTk3OTkyLCJpYXQiOjE3Mzc5MTE1OTJ9.REvEi9Sy2IVxivyCEJcBtz-NGPlk5I1eqpqf2ysNegU
Content-Type: application/json

###

POST {{RoomBooking_Back__HostAddress}}/booking/
Content-Type: application/json

{
    "NewBooking": {
        "Name": "Réunion Mensuelle",
        "IdRoom": 1,
        "IdOrganizer": 1,
        "DateFrom": "2025-02-01T14:00:00",
        "DateTo": "2025-02-01T15:00:00"
    },
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwiZW1haWwiOiJhdXJlbGllLnJ1bnNlcjI1QGdtYWlsLmNvbSIsIm5iZiI6MTczOTgxNTQ0MiwiZXhwIjoxNzM5OTAxODQyLCJpYXQiOjE3Mzk4MTU0NDJ9.jQB6phxyUZcQJvxTFbVVC0dkFt1XffeOw_y9jfJM_10
}

###

POST {{RoomBooking_Back__HostAddress}}/booking/
Content-Type: application/json

{
    "NewBooking": {
        "Name": "Réunion 2",
        "IdRoom": 2,
        "IdOrganizer": 1,
        "DateFrom": "2025-02-02T14:00:00",
        "DateTo": "2025-02-02T15:00:00"
    },
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwiZW1haWwiOiJhdXJlbGllLnJ1bnNlcjI1QGdtYWlsLmNvbSIsIm5iZiI6MTczOTgxNTQ0MiwiZXhwIjoxNzM5OTAxODQyLCJpYXQiOjE3Mzk4MTU0NDJ9.jQB6phxyUZcQJvxTFbVVC0dkFt1XffeOw_y9jfJM_10"
}

###

POST {{RoomBooking_Back__HostAddress}}/booking/
Content-Type: application/json

{
    "NewBooking": {
        "Name": "Réunion 2",
        "IdRoom": 5,
        "IdOrganizer": 2,
        "DateFrom": "2025-02-02T14:00:00",
        "DateTo": "2025-02-02T15:00:00"
    },
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwiZW1haWwiOiJhdXJlbGllLnJ1bnNlcjI1QGdtYWlsLmNvbSIsIm5iZiI6MTczOTgxNTQ0MiwiZXhwIjoxNzM5OTAxODQyLCJpYXQiOjE3Mzk4MTU0NDJ9.jQB6phxyUZcQJvxTFbVVC0dkFt1XffeOw_y9jfJM_10"
}

###

POST {{RoomBooking_Back__HostAddress}}/booking/
Content-Type: application/json

{
    "NewBooking": {
        "Name": "Réunion zoedfr",
        "IdRoom": 1,
        "IdOrganizer": 1,
        "DateFrom": "2024-02-02T14:00:00",
        "DateTo": "2024-02-02T15:00:00"
    },
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwiZW1haWwiOiJhdXJlbGllLnJ1bnNlcjI1QGdtYWlsLmNvbSIsIm5iZiI6MTczOTgxNTQ0MiwiZXhwIjoxNzM5OTAxODQyLCJpYXQiOjE3Mzk4MTU0NDJ9.jQB6phxyUZcQJvxTFbVVC0dkFt1XffeOw_y9jfJM_10
}